
development:
  adapter: postgresql
  encoding: unicode
  database: real_estate_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: real_estate_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: real_estate_production
  pool: 5
  username:
  password:
